spring:
  application:
    name: auth-service
server:
  port: 9100
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address
