server:
  port: 8001

spring:
  application:
    name: api-gateway

zuul:
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders: Cookie, Set-Cookie
    user-service:
      path: /users/**
      serviceId: user-service
    book-service:
      path: /books/**
      serviceId: book-service
    review-service:
      path: /reviews/**
      serviceId: review-service

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

security:
  jwt:
    uri: /auth/**
    header: Token
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey
