server:
  port: 8762

spring:
  application:
    name: api-gateway

zuul:
  routes:
    auth-service:
      path: /**
      serviceId: auth-service
      sensitiveHeaders: Cookie, Set-Cookie
      stripPrefix: false
    user-service:
      path: /**
      serviceId: user-service
      stripPrefix: false
    book-service:
      path: /**
      serviceId: book-service
      stripPrefix: false

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey
