spring:
  profiles:
    active: common
  application:
    name: alert-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: #username
    password: #password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true

kafka:
  bootstrapServers: 3.35.229.19:9092
  topic:
    rent:
      name: book-rent-topic
    return:
      name: book-return-topic
  consumer:
    rent:
      alert:
        groupName: book-rent-alert-group
      mail:
        groupName: book-rent-mail-group
    return:
      alert:
        groupName: book-return-alert-group
      mail:
        groupName: book-return-mail-group

logging:
  level:
    org.hibernate.type: debug

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  eureka:
    enabled: true

security:
  jwt:
    uri: /auth/**
    header: Token
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey

server:
  port: 8006

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:~/alert-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console

---
spring:
  profiles: release
  datasource:
    url: jdbc:mysql://mysql-ip:3306/alert?serverTimezone=UTC&characterEncoding=UTF-8
    username: #username
    password: #password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update


