server:
  port: 8006

spring:
  application:
    name: alert-service
  datasource:
    url: jdbc:h2:~/alert-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /console

  cloud:
    stream:
      kafka:
        binder:
          brokers: 3.35.229.19
          zkNodes: 3.35.229.19
          defaultBrokerPort: 9092
          autoCreateTopics: false
      bindings:
        book-rent-alert-consumer:
          destination: book-rent-topic
          content-type: application/json
          group: book-rent-alert-group
          binder: kafka
        book-rent-mail-consumer:
          destination: book-rent-topic
          content-type: application/json
          group: book-rent-mail-group
          binder: kafka
  mail:
    host: smtp.gmail.com
    port: 587
    username: #username
    password: #password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
logging:
  level:
    org.hibernate.type: debug

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  eureka:
    enabled: true

security:
  jwt:
    uri: /auth/**
    header: Token
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey
